require:
  - rubocop/cop/internal_affairs

inherit_from:
  - ./config/default.yml

InternalAffairs/CopDescription:
  Enabled: true

InternalAffairs/EmptyLineBetweenExpectOffenseAndCorrection:
  Enabled: true

InternalAffairs/ExampleDescription:
  Enabled: true

InternalAffairs/InheritDeprecatedCopClass:
  Enabled: true

InternalAffairs/LocationLineEqualityComparison:
  Enabled: true

InternalAffairs/MethodNameEndWith:
  Enabled: true

InternalAffairs/MethodNameEqual:
  Enabled: true

InternalAffairs/NodeDestructuring:
  Enabled: true

InternalAffairs/NodeMatcherDirective:
  Enabled: true

InternalAffairs/NodeTypePredicate:
  Enabled: true

InternalAffairs/NumblockHandler:
  Enabled: true

InternalAffairs/OffenseLocationKeyword:
  Enabled: true

InternalAffairs/RedundantContextConfigParameter:
  Enabled: true

InternalAffairs/RedundantDescribedClassAsSubject:
  Enabled: true

InternalAffairs/RedundantLetRuboCopConfigNew:
  Enabled: true

InternalAffairs/RedundantLocationArgument:
  Enabled: true

InternalAffairs/RedundantMessageArgument:
  Enabled: true

InternalAffairs/RedundantMethodDispatchNode:
  Enabled: true

InternalAffairs/SingleLineComparison:
  Enabled: true

InternalAffairs/StyleDetectedApiUse:
  Enabled: true

InternalAffairs/UselessMessageAssertion:
  Enabled: true

InternalAffairs/UselessRestrictOnSend:
  Enabled: true

Naming/FileName:
  Enabled: true
  Exclude:
    - "rubocop-github.gemspec"
    - "lib/rubocop-github.rb"
    - "lib/rubocop-github-rails.rb"
