require "rubocop/cop/github/rails_application_record"
require "rubocop/cop/github/rails_controller_render_paths_exist"
require "rubocop/cop/github/rails_render_inline"
require "rubocop/cop/github/rails_render_object_collection"
require "rubocop/cop/github/rails_view_render_paths_exist"
