Rails/ActionControllerFlashBeforeRender: # new in 2.16
  Enabled: false
Rails/ActionOrder: # new in 2.17
  Enabled: false
Rails/ActiveSupportOnLoad: # new in 2.16
  Enabled: false
Rails/FreezeTime: # new in 2.16
  Enabled: false
Rails/IgnoredColumnsAssignment: # new in 2.17
  Enabled: false
Rails/RootPathnameMethods: # new in 2.16
  Enabled: false
Rails/ToSWithArgument: # new in 2.16
  Enabled: false
Rails/TopLevelHashWithIndifferentAccess: # new in 2.16
  Enabled: false
Rails/WhereMissing: # new in 2.16
  Enabled: false
Rails/WhereNotWithMultipleConditions: # new in 2.17
  Enabled: false
Rails/DangerousColumnNames: # new in 2.21
  Enabled: false
Rails/EnvLocal: # new in 2.22
  Enabled: false
Rails/RedundantActiveRecordAllMethod: # new in 2.21
  Enabled: false
Rails/ResponseParsedBody: # new in 2.18
  Enabled: false
Rails/ThreeStateBooleanColumn: # new in 2.19
  Enabled: false
Rails/UnusedRenderContent: # new in 2.21
  Enabled: false
Rails/EnumSyntax: # new in 2.26
  Enabled: false
Rails/WhereRange: # new in 2.25
  Enabled: false
Rails/FindByOrAssignmentMemoization: # new in 2.33
  Enabled: true
Rails/HttpStatusNameConsistency: # new in 2.34
  Enabled: true
Rails/MultipleRoutePaths: # new in 2.29
  Enabled: true
Rails/OrderArguments: # new in 2.33
  Enabled: true
Rails/RedirectBackOrTo: # new in 2.34
  Enabled: true
Rails/StrongParametersExpect: # new in 2.29
  Enabled: true
