require:
  - rubocop-rails
  - rubocop/cop/standard/rails

Rails/OutputSafety:
  Enabled: true

Rails/PluralizationGrammar:
  Enabled: true

Rails/RequestReferer:
  Enabled: true
  EnforcedStyle: referrer

Rails/ScopeArgs:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

Standard/RailsApplicationRecord:
  Enabled: true

Standard/RailsControllerRenderActionSymbol:
  Enabled: true
  Include:
    - "app/controllers/**/*.rb"

Standard/RailsControllerRenderLiteral:
  Enabled: true
  StyleGuide: https://Standard.com/Standard/rubocop-Standard/blob/master/guides/rails-render-literal.md
  Include:
    - "app/controllers/**/*.rb"

Standard/RailsControllerRenderPathsExist:
  Enabled: true
  ViewPath:
    - "app/views"
  Include:
    - "app/controllers/**/*.rb"

Standard/RailsControllerRenderShorthand:
  Enabled: true
  StyleGuide: https://Standard.com/Standard/rubocop-Standard/blob/master/guides/rails-controller-render-shorthand.md
  Include:
    - "app/controllers/**/*.rb"

Standard/RailsRenderInline:
  Enabled: true
  StyleGuide: https://Standard.com/Standard/rubocop-Standard/blob/master/guides/rails-controller-render-inline.md
  Include:
    - "app/controllers/**/*.rb"
    - "app/helpers/**/*.rb"
    - "app/view_models/**/*.rb"
    - "app/views/**/*.erb"

Standard/RailsRenderObjectCollection:
  Enabled: false

Standard/RailsViewRenderLiteral:
  Enabled: true
  StyleGuide: https://Standard.com/Standard/rubocop-Standard/blob/master/guides/rails-render-literal.md
  Include:
    - "app/helpers/**/*.rb"
    - "app/view_models/**/*.rb"
    - "app/views/**/*.erb"

Standard/RailsViewRenderPathsExist:
  Enabled: true
  ViewPath:
    - "app/views"
  Include:
    - "app/helpers/**/*.rb"
    - "app/view_models/**/*.rb"
    - "app/views/**/*.erb"

Standard/RailsViewRenderShorthand:
  Enabled: true
  Include:
    - "app/helpers/**/*.rb"
    - "app/view_models/**/*.rb"
    - "app/views/**/*.erb"

# Exclude Rails ERB files from incompatible cops

Layout/BlockAlignment:
  Exclude:
    - "app/views/**/*.erb"

Style/For:
  Exclude:
    - "app/views/**/*.erb"

Style/OneLineConditional:
  Exclude:
    - "app/views/**/*.erb"

Style/Semicolon:
  Exclude:
    - "app/views/**/*.erb"

Layout/SpaceInsideParens:
  Exclude:
    - "app/views/**/*.erb"

Style/StringLiterals:
  Exclude:
    - "app/views/**/*.erb"

Layout/TrailingBlankLines:
  Exclude:
    - "app/views/**/*.erb"

Layout/TrailingWhitespace:
  Exclude:
    - "app/views/**/*.erb"

Layout/InitialIndentation:
  Exclude:
    - "app/views/**/*.erb"

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - concerning
