name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - uses: ruby/setup-ruby@19a43a6a2428d455dbd1b85344698725179c9d8c # pin@v1.289.0
        with:
          bundler-cache: true

      - name: build
        run: |
          GEM_NAME=$(ls | grep gemspec | cut -d. -f1)
          echo "Attempting to build gem $GEM_NAME..."
          gem build $GEM_NAME
          if [ $? -eq 0 ]; then
            echo "Gem built successfully!"
          else
            echo "Gem build failed!"
            exit 1
          fi
