name: CI
permissions:
  contents: read

on: pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.0", "3.1", "3.2", "3.3"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update .ruby-version with matrix value
        run: echo "${{ matrix.ruby_version }}" >| .ruby-version
      - name: Set up Ruby
        uses: ruby/setup-ruby@f26937343756480a8cb3ae1f623b9c8d89ed6984
        with:
          bundler-cache: true
          rubygems: latest
      - name: Run tests
        run: bundle exec rake
