name: CI
permissions:
  contents: read

on: pull_request

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.0", "3.1", "3.2", "3.3"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update .ruby-version with matrix value
        run: echo "${{ matrix.ruby_version }}" >| .ruby-version
      - name: Set up Ruby
        uses: ruby/setup-ruby@2654679fe7f7c29875c669398a8ec0791b8a64a1
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
