name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - uses: ruby/setup-ruby@bec3f19a76460dbe12f60def7d1a77585f07516c # pin@v1.322.0
        with:
          bundler-cache: true

      - name: lint
        run: script/lint
