name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # pin@v1.312.0
        with:
          bundler-cache: true

      - name: lint
        run: script/lint
