name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ruby/setup-ruby@e8944e80fb94b20106697132f8c20c665fab29e9 # pin@v1.325.0
        with:
          bundler-cache: true

      - name: lint
        run: script/lint
