name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.3", "3.4", "4.0"]

    steps:
      - uses: actions/checkout@v6

      - name: Update .ruby-version with matrix value
        run: echo "${{ matrix.ruby_version }}" >| .ruby-version

      - uses: ruby/setup-ruby@a99ac844649df2596b52b4db087cfa0881b172af # pin@v1.311.0
        with:
          bundler-cache: true

      - name: test
        run: script/test
