name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.3", "3.4", "4.0"]

    steps:
      - uses: actions/checkout@v7

      - name: Update .ruby-version with matrix value
        run: echo "${{ matrix.ruby_version }}" >| .ruby-version

      - uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # pin@v1.318.0
        with:
          bundler-cache: true

      - name: test
        run: script/test
