name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.3", "3.4", "4.0"]

    steps:
      - uses: actions/checkout@v7

      - name: Update .ruby-version with matrix value
        run: echo "${{ matrix.ruby_version }}" >| .ruby-version

      - uses: ruby/setup-ruby@a0102e0972be65f351c307e2d64b9314a57c8073 # pin@v1.324.0
        with:
          bundler-cache: true

      - name: test
        run: script/test
